apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-task
spec:
  steps:
    - name: build
      image: maven:3.8.1-openjdk-11
      script: |
        #!/bin/sh
        mvn clean package -DskipTests
      workingDir: /workspace/source
      volumeMounts:
        - name: source
          mountPath: /workspace/source
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-name
