apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/bin/sh
        oc new-app your-repo/your-app:latest
        oc expose svc/your-app
      workingDir: /workspace/source
      volumeMounts:
        - name: source
          mountPath: /workspace/source
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-name

