apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cucumber-pipeline
spec:
  tasks:
    - name: build
      taskRef:
        name: build-task
    - name: deploy
      taskRef:
        name: deploy-task
      runAfter:
        - build
    - name: test
      taskRef:
        name: test-task
      runAfter:
        - deploy
