apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: test
      image: maven:3.8.1-openjdk-11
      script: |
        #!/bin/sh
        mvn test
      workingDir: /workspace/source
      volumeMounts:
        - name: source
          mountPath: /workspace/source
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-name
